### ISSUE TITLE
panic: Error fetching certificate from non-default namespace

### ISSUE THREAD

**Issue by gkarthiks** [bitnami-labs/sealed-secrets#125]
I have deployed the `sealed-secrets` in my OpenShift cluster, but not under `kube-system` namespace, under the namespace `sealed-secrets`.

But the deployments are successful, could see the public key in the log. Now if I execute the below command, I get the panic error as shown beneath that.

#### Command: 
```
kubeseal --fetch-cert
```
#### Response:
```
panic: Error fetching certificate: services "sealed-secrets-controller" not found

goroutine 1 [running]:
main.main()
	/Users/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:216 +0x3b9
```

<br/><br/><br/>

#### Command:
```
kubeseal --fetch-cert -n sealed-secrets
```

#### Response:
```
panic: Error fetching certificate: services "sealed-secrets-controller" not found

goroutine 1 [running]:
main.main()
	/Users/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:216 +0x3b9
```

<br/><br/><br/>

#### Command:
```
kubeseal --fetch-cert -n sealed-secrets --kubeconfig ~/.kube/config
```

#### Response:
```
panic: Error fetching certificate: services "sealed-secrets-controller" not found

goroutine 1 [running]:
main.main()
	/Users/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:216 +0x3b9
```

**Comment by gkarthiks** [comment]
sorry, figured. Need to send the `--controller-namespace` string.
