### ISSUE TITLE
kubeseal fails on new install to read local cert file

### ISSUE THREAD

**Issue by KlavsKlavsen** [bitnami-labs/sealed-secrets#531]
I installed sealed-secrets via helm - and got my pub-cert file out.. openssl x509 can read it just fine.
When I then try to use kubeseal with it it fails:
```
$ kubeseal --cert secret-certificate.pem <mysecret.json >mysealedsecret.json
panic: attempted to parse unknown event: none [recovered]
        panic: attempted to parse unknown event: none

goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc0000ef968)
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/vendor/gopkg.in/yaml.v2/yaml.go:249 +0x9a
panic(0x10c2d00, 0xc000324f20)
        /home/travis/.gimme/versions/go1.14.14.linux.amd64/src/runtime/panic.go:969 +0x166
gopkg.in/yaml%2ev2.(*parser).parse(0xc0002d4900, 0xc0003089c0)
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/vendor/gopkg.in/yaml.v2/decode.go:158 +0x251
gopkg.in/yaml%2ev2.(*Decoder).Decode(0xc0000ef998, 0x1093860, 0x1cb1828, 0x0, 0x0)
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/vendor/gopkg.in/yaml.v2/yaml.go:122 +0xdf
github.com/bitnami-labs/sealed-secrets/pkg/multidocyaml.isMultiDocumentYAML(0xc00004ac00, 0xd5, 0x600, 0x0)
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/pkg/multidocyaml/multidocyaml.go:14 +0x1f1
github.com/bitnami-labs/sealed-secrets/pkg/multidocyaml.EnsureNotMultiDoc(0xc00004ac00, 0xd5, 0x600, 0xc00004ac00, 0xd5)
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/pkg/multidocyaml/multidocyaml.go:19 +0x43
main.readSecret(0x7f9e3be3d390, 0xc0000d25a0, 0x13d53a0, 0xc00000e010, 0x13d4b80, 0xc000246280, 0xc000001500)
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:139 +0x8c
main.seal(0x13d53a0, 0xc00000e010, 0x13d53c0, 0xc00000e018, 0xc0000f4bd0, 0xc000255200, 0x3, 0x3, 0x13d4b80, 0xc000246280, ...)
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:243 +0xa6
main.run(0x13d53c0, 0xc00000e018, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x124c6f2, 0xb, ...)
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:719 +0x947
main.main()
        /home/travis/gopath/src/github.com/bitnami-labs/sealed-secrets/cmd/kubeseal/main.go:726 +0x336
```

**Comment by KlavsKlavsen** [comment]
I had manually added namespace to mysecret.json and probably made improper json by doing this.. So above seems to be caused by an invalid json. You should probably check for valid json and complain "nicely" about that :)
